/** Shared personnel supplied by the owner; new director titles assigned at their request. */
export const leadershipTeam = [
  {
    code: "01",
    name: "George Copeland",
    role: "CEO",
    title: "Chief Executive Officer",
    image: "/images/george.jpg",
    objectPosition: "center 20%",
    alt: "George Copeland — Chief Executive Officer",
    description: "Strategic direction, enterprise growth, and executive governance across international infrastructure and technology programs.",
  },
  {
    code: "02",
    name: "Yannick sani",
    role: "CTO",
    title: "Chief Technology Officer",
    image: "/images/yannick.jpeg",
    objectPosition: "center 25%",
    alt: "Yannick sani — Chief Technology Officer",
    description: "Enterprise systems architecture, cloud infrastructure, datacenter engineering, and mission-critical cybersecurity frameworks.",
  },
  {
    code: "03",
    name: "Bienvenu Owono",
    role: "CPO",
    title: "Chief Product Officer",
    image: "/images/joseph-bienvenu.jpg",
    objectPosition: "center center",
    alt: "Bienvenu Owono — Chief Product Officer",
    description: "Product innovation, TASHA autonomous AI multi-agent platform engineering, and enterprise solutions architecture.",
  },
  {
    code: "04",
    name: "Scarlett Patricia",
    role: "OPERATIONS",
    title: "Operations Director",
    image: "/images/patricia.jpg",
    objectPosition: "center center",
    alt: "Scarlett Patricia — Operations Director",
    description: "Operational coordination, service delivery, and alignment of teams across technology programs.",
  },
  {
    code: "05",
    name: "Christina Harper",
    role: "CLIENT RELATIONS",
    title: "Client Relations Director",
    image: "/images/christina.jpg",
    objectPosition: "center 35%",
    alt: "Christina Harper — Client Relations Director",
    description: "Client communication, relationship management, and coordination of customer needs with delivery teams.",
  },
];
