import { DatabaseSync } from "node:sqlite";
import fs from "node:fs";
import path from "node:path";
const file = path.join(process.cwd(), "data", "linuzvision.db");
if (!fs.existsSync(file)) throw new Error("Database has not been initialized. Start or build the application first.");
const db = new DatabaseSync(file, { readOnly: true });
const integrity = db.prepare("PRAGMA integrity_check").get();
const insights = db.prepare("SELECT COUNT(*) AS count FROM insights").get();
const inquiries = db.prepare("SELECT COUNT(*) AS count FROM inquiries").get();
console.log(JSON.stringify({ integrity: integrity.integrity_check, insights: insights.count, inquiries: inquiries.count }, null, 2));
